---
- name: Build virtual user database
  ansible.builtin.command:
    cmd: "db_load -T -t hash -f /etc/vsftpd/virtual_users.txt /etc/vsftpd/virtual_users.db"
  changed_when: true

- name: Restart vsftpd
  ansible.builtin.service:
    name: vsftpd
    state: restarted
